Added cqrs
PTSS-Support/PTSS-Support-Quarkus-Base-Repo pull request #10
Opened 2024-12-06 13:27 UTC by DaanTol

2024-12-06 14:32 UTC, SemPlaatsman requested changes
Een Product heeft een id, name, description, en media array met string items (uri's). 
Change accordingly. 

Ik zie veel duplicate code van `return try { ... } catch (ex: Exception) { logger.error(...) throw ex }`. Vervang dit mogelijk met een errorHandling helper class zoals [dit](https://github.com/SemPlaatsman/WidgetCo.Store/blob/main/WidgetCo.Store.Infrastructure/Util/ExceptionLogging.cs).

2024-12-06 15:19 UTC, SemPlaatsman requested changes
Ziet er perfect uit maar kan je de `executeWithExceptionLoggingAsync` nog even veranderen naar iets zoals [dit](https://claude.site/artifacts/b3a13c18-d285-4815-a34e-2a33656b7e02)?

Dan is [deze syntax](https://claude.site/artifacts/9a7f2edb-0e2c-4fd3-8479-c5c578d6456d) namelijk mogelijk (vlgns mij, don't quote me on this) en kan je [dit veranderen](https://claude.site/artifacts/36469d76-be3d-4b1a-89b3-56f849a895d7).

2024-12-06 15:23 UTC, Tayam-El-Jebari requested changes

2024-12-06 15:23 UTC, Tayam-El-Jebari commented on src/main/kotlin/cqrs/core/commands/ProductCommands.kt
> +import java.math.BigDecimal
unused import

2024-12-06 15:23 UTC, Tayam-El-Jebari commented on src/main/kotlin/cqrs/core/dtos/ProductDto.kt
> +import java.math.BigDecimal
unused import

2024-12-06 15:23 UTC, Tayam-El-Jebari commented on src/main/kotlin/cqrs/core/models/Product.kt
> +import java.util.*
wild card import, please change to only use UUID

2024-12-06 15:23 UTC, Tayam-El-Jebari commented on src/main/kotlin/cqrs/core/models/Product.kt
> +import java.math.BigDecimal
unused import again

2024-12-06 15:23 UTC, Tayam-El-Jebari commented on src/main/kotlin/cqrs/core/queries/ProductQueries.kt
> +data class GetAllProductsQuery(val placeholder: Boolean = true)
why placeholder? Why does it default to true?

2024-12-06 15:23 UTC, Tayam-El-Jebari commented on src/main/kotlin/cqrs/core/queries/ProductQueries.kt
> +data class GetAllProductsQuery(val placeholder: Boolean = true)
not sure what the Boolean does yet, but if there's a default value, then it could also just be a boolean (with small b) as it can never be null, no?

2024-12-06 15:23 UTC, Tayam-El-Jebari commented on src/main/kotlin/cqrs/infrastructure/handlers/queries/ProductQueryHandlers.kt
why have two classes in one file?

2024-12-06 16:12 UTC, SemPlaatsman requested changes

2024-12-06 16:12 UTC, SemPlaatsman commented on src/main/kotlin/cqrs/infrastructure/handlers/queries/ProductQueryHandlers.kt
Deze moeten idd opgesplitst worden in `GetProductByIdQueryHandler.kt` en `GetAllProductsQueryHandler.kt` (in maybe een Product folder)

2024-12-06 16:12 UTC, SemPlaatsman commented on src/main/kotlin/cqrs/infrastructure/services/ProductService.kt
Waarom heb je mijn example comments er nog bijgelaten??

2024-12-06 16:12 UTC, SemPlaatsman commented on src/main/kotlin/cqrs/infrastructure/handlers/queries/ProductQueryHandlers.kt
Kan de executeWithLoggingAsync function gebruiken

2024-12-06 16:12 UTC, SemPlaatsman commented on src/main/kotlin/cqrs/infrastructure/handlers/commands/ProductCommandHandler.kt
Kan de executeWithLoggingAsync function gebruiken

2024-12-06 16:12 UTC, SemPlaatsman commented on src/main/kotlin/cqrs/infrastructure/handlers/commands/ProductCommandHandler.kt
Dit moest ook in een eigen file (`CreateProductCommandHandler.kt`)

Dus ipv: handlers/commands/ProductCommandHandlers.kt, ditte: handlers/commands/Product/CreateProductCommandHandler.kt

2024-12-06 16:12 UTC, SemPlaatsman commented on src/main/kotlin/cqrs/infrastructure/handlers/queries/ProductQueryHandlers.kt
Dit moest nog opgesplitst worden in eigen files (`GetProductByIdQueryHandler.kt` en `GetAllProductsQueryHandler.kt`)

Dus ipv: handlers/queries/ProductQueryHandlers.kt, ditte: handlers/queries/Product/GetProductByIdQueryHandler.kt en handlers/queries/Product/GetAllProductsQueryHandler.kt

2024-12-06 21:11 UTC, SemPlaatsman approved these changes

2024-12-07 16:41 UTC, Tayam-El-Jebari approved these changes

2024-12-07 16:42 UTC, merged