Spotless making use of ktlint linting
PTSS-Support/PTSS-Support-Quarkus-Base-Repo pull request #61
Opened 2024-12-11 14:39 UTC by Bastiaan27

WIP!! PR is up for other people to take a look

- Added spotless configured to use ktlint for quarkus kotlin code
- Added docs, with a doc on how to use spotless
- Removed detekt from previous commit
- Still needs a github hook to run a format with every commit
- Haven't figured out how to link sonarqube locally, and if it's necessary at all

2024-12-11 23:13 UTC, SemPlaatsman requested changes
Voeg nog de code voor een pre-commit hook toe (of een alternatieve methode, als je een betere kan vinden). 

Verder ziet het er heel goed uit, lekker bezig

2024-12-12 13:26 UTC, Tayam-El-Jebari requested changes, later dismissed
branch is very out of date, please update before finishing as some of the files are outdated (e.g. productdto has long been removed)

2024-12-12 23:00 UTC, SemPlaatsman requested changes

2024-12-12 23:00 UTC, SemPlaatsman commented on .github/workflows/deploy-dev.yml
> +    if: ${{ !github.event.repository.created }}  # Only run if NOT repository creation
Dit moet er even uit, is nog oude code

2024-12-12 23:00 UTC, SemPlaatsman commented on .github/workflows/deploy-prod.yml
> +    if: ${{ !github.event.repository.created }}  # Only run if NOT repository creation
Moet er ook uit; oude code

2024-12-12 23:00 UTC, SemPlaatsman commented on docs/sonarqube-local.md
> +    - The issues identified by SonarQube for IDE will appear in the **SonarQube for IDE Report** window.
Heb je dit getest via IntelliJ IDEA? Ik zou aanraden om IntelliJ IDEA ipv VSCode te gebruiken btw

2024-12-12 23:14 UTC, Bastiaan27 commented on docs/sonarqube-local.md
> +    - The issues identified by SonarQube for IDE will appear in the **SonarQube for IDE Report** window.
Ja, ik heb die guide ook geschreven mbv IntellIJ

2024-12-12 23:14 UTC, Bastiaan27 commented on docs/sonarqube-local.md
> +    - The issues identified by SonarQube for IDE will appear in the **SonarQube for IDE Report** window.
Het werkt en highlight dezelfde issues als die je in de web portal ziet

2024-12-13 11:43 UTC, SemPlaatsman approved these changes

2024-12-13 12:34 UTC, DaanTol approved these changes

2024-12-13 13:18 UTC, merged