Feature/codeql
PTSS-Support/PTSS-Support-Quarkus-Base-Repo pull request #62
Opened 2024-12-11 17:19 UTC by DaanTol

Testing if a alert occurs

2024-12-11 17:46 UTC, SemPlaatsman submitted a review, later dismissed

2024-12-11 19:57 UTC, SemPlaatsman approved these changes

2024-12-12 01:12 UTC, SemPlaatsman requested changes

2024-12-12 01:12 UTC, SemPlaatsman commented on CI-CD.md
> +`.github/workflows/pr-validation.yml`
Niet echt nodig om te benoemen, dit staat namelijk onder het PR Validation stukje

2024-12-12 01:12 UTC, SemPlaatsman commented on CI-CD.md
> +    - `security-and-quality`
Waarom deze twee? En waarom niet meer? Elke keuze kan goed zijn, zolang het maar verantwoord is

2024-12-12 12:10 UTC, SemPlaatsman approved these changes

2024-12-12 13:28 UTC, Tayam-El-Jebari approved these changes

2024-12-12 13:28 UTC, Tayam-El-Jebari commented on .github/workflows/pr-validation.yml
> +          languages: java  # Change to 'java' since Kotlin is analyzed as Java
this comment is unnecessary

2024-12-12 13:28 UTC, Tayam-El-Jebari commented on CI-CD.md
> +       languages: java,python  # Add new languages here
python?

2024-12-12 13:34 UTC, merged