Feature/k6
PTSS-Support/PTSS-Support-Quarkus-Base-Repo pull request #7
Opened 2024-12-06 11:56 UTC by RamonKea-inh

2024-12-06 14:12 UTC, SemPlaatsman requested changes
De k6 tests moeten in de `src/test/kotlin/org/ptss/support/k6` folder. 

Het is meer best practice om je k6 files op te delen in meerdere files en directories. Je kan bijvoorbeeld ervoor zorgen dat je in de k6 folder een options.js, config.js, en andere default k6 files hebt, en dan heb je in je k6 folder een tests folder waarin de daadwerkelijke tests toegevoegd kunnen worden. Hier is een voorbeeld:
```
src/test/kotlin/org/ptss/support/k6/
├── config.js           # Configuration variables
├── metrics.js          # Shared custom metrics
├── options.js          # Default test options
└── tests/
    ├── health.js      # Health check tests
    └── products.js    # Product-related endpoint tests
```

2024-12-06 16:04 UTC, SemPlaatsman requested changes
Gebruik het daadwerkelijke voorbeeld voor load testing ipv een fake API URL en PAYLOAD te gebruiken. De requests staan in Insomnia en er is een setup guide in `INSOMNIA.md`. Als je het niet kan vinden is [hier nog een link](https://pastebin.com/g3CrrTd7).

2024-12-08 15:26 UTC, SemPlaatsman requested changes
/test/success hoort niet tot de implementatie. Gebruik de health endpoint van Smallrye. [Zie voorbeeld](https://claude.site/artifacts/f702e01e-7680-4cd0-b12f-de7f6a764a56).

2024-12-08 18:25 UTC, SemPlaatsman approved these changes

2024-12-08 20:14 UTC, Tayam-El-Jebari approved these changes

2024-12-08 20:23 UTC, merged