made dockerfile, added deployment script to check if it worked.
PTSS-Support/PTSS-Support-Quarkus-Base-Repo pull request #8
Opened 2024-12-06 12:00 UTC by Tayam-El-Jebari

2024-12-06 13:44 UTC, SemPlaatsman requested changes

2024-12-06 13:44 UTC, SemPlaatsman commented on Dockerfile
Wordt deze dockerfile ook gebruikt bij development of is het alleen voor het deployen? Liever ook voor development namelijk.

Waarom wordt er geen docker-compose.yml gebruikt?

Ondersteund deze docker setup hot-reload?

2024-12-06 14:39 UTC, Tayam-El-Jebari commented on Dockerfile
dockerfile is puur en alleen voor deployen, nothing more, nothing less. Lokaal gebruik je het niet 

Docker-compose.yml is voor het daadwerkelijk runnen van een docker container lokaal. Wat zou je lokaal willen runnen tho? Ik zie docker-compose.yml alleen als nuttig zodra je lokaal wilt testen met bijvoorbeeld een sql server, of een andere mogelijke database dat je wilt faken. Aangezien de uitbreiding er nog niet is, lijkt het me niet deel van deze taak en sws gebruiken we table storage en blob storage voornamelijk, daar gebruik je toch geen docker voor?

"Ondersteund deze docker setup hot-reload?" Well, what do you mean? Want nee dat doet het niet, maar waarom zou je dat hebben op een deployment?

2024-12-06 16:00 UTC, SemPlaatsman requested changes

2024-12-06 16:00 UTC, SemPlaatsman commented on docker-compose.yaml
Liever een .env(.dev/.prod) gebruiken ipv hardcoded secrets (voeg ook .env.example toe die niet gitignored is). 

Maybe ook even naar dit kijken:


Avoid Hardcoded Ports:
* Let OpenShift handle port mappings dynamically.
* Expose ports using:
```dockerfile
EXPOSE 8080 5005
```

2024-12-06 17:27 UTC, Tayam-El-Jebari commented on docker-compose.yaml
Good point on .env, moved the secrets to there.
docker-compose.yaml isn't used by openshift tho? Or are you talking about the dockerfile?

2024-12-06 17:50 UTC, SemPlaatsman approved these changes
🫡

2024-12-06 17:50 UTC, SemPlaatsman commented on docker-compose.yaml
U right, OSC does not use `docker-compose.yml` so not needed. 
But can u make an .env.example pls daddy

2024-12-07 11:43 UTC, SemPlaatsman approved these changes

2024-12-07 12:37 UTC, merged