Feature/updating authentication filters
PTSS-Support/PTSS-Support-Quarkus-Base-Repo pull request #81
Opened 2024-12-27 19:53 UTC by Tayam-El-Jebari

made it so the only check you have to do at service is check if roles are valid and if token is expired

Rest of authorisation flow should be done in the authentication service/ gateway

2024-12-28 18:37 UTC, SemPlaatsman requested changes

2024-12-28 18:37 UTC, SemPlaatsman commented on src/main/kotlin/org/ptss/support/infrastructure/util/cookieUtil.kt
> +) {
Dit zou ik in een CookieProperties file doen in domain/config ofzo.

2024-12-28 18:37 UTC, SemPlaatsman commented on src/main/kotlin/org/ptss/support/infrastructure/util/cookieUtil.kt
> +    }
Waarom wordt dit in een util function gezet als het maar op één plek gebruikt wordt?

2024-12-28 18:37 UTC, SemPlaatsman commented on src/main/kotlin/org/ptss/support/security/JwtValidator.kt
> +            val jsonObject = ObjectMapper().readTree(payload)
Wordt dit deel niet al gedaan door `jwtParser.parse(token)`. Waarom manually doen als je er een library voor hebt die het voor je kan doen en wss ook meer reliable.

2024-12-28 18:37 UTC, SemPlaatsman commented on src/main/kotlin/org/ptss/support/security/TokenUserExtractor.kt
Meeste hiervan zou net zo goed door een library gedaan kunnen worden right?

2025-01-04 22:46 UTC, Tayam-El-Jebari commented on src/main/kotlin/org/ptss/support/infrastructure/util/cookieUtil.kt
> +    }
klopt idd, brein was op autopilot en nam dingen over van auth service

2025-01-04 22:46 UTC, Tayam-El-Jebari commented on src/main/kotlin/org/ptss/support/security/JwtValidator.kt
> +            val jsonObject = ObjectMapper().readTree(payload)
jup, tru again, autopilot plus claude hallucinaties zorge ervoor dat ik hallucineerde lol, heel jwtvalidator is niet echt nodig, even anders aangepakt met tokenextractor dat zolang de jwt geldig is, rollen terug stuurt, anders nada

2025-01-04 23:59 UTC, SemPlaatsman approved these changes

2025-01-05 00:02 UTC, merged